### ISSUE TITLE
update getting_started notebook with cudf

### ISSUE THREAD

**Issue by sarthfrey** [rapidsai/notebooks#1]
Update the getting_started.ipynb notebook with the new cudf release to work with the standard cudf docker container.

**Comment by sarthfrey** [comment]
Similar to notebook here: https://github.com/gpuopenanalytics/demo-docker/blob/master/notebook-demo-docker/demo/notebooks/getting_started.ipynb

**Comment by mike-wendt** [comment]
Test notebook with CUDA 9.2 image from here to ensure no errors are found https://hub.docker.com/r/rapidsai/rapidsai

**Comment by sarthfrey** [comment]
Confirmed notebook runs on rapidsai container for `cuda9.2_ubuntu16.04` and `cuda10.0_ubuntu16.04`

**Comment by taureandyernv** [comment]
Closed as tests on update were successful
