### ISSUE TITLE
E2E Mortgage demo : running from 2000 to 2001 on 8 parts does not work

### ISSUE THREAD

**Issue by cicyle** [rapidsai/notebooks#104]
data:
http://rapidsai-data.s3-website.us-east-2.amazonaws.com/notebook-mortgage-data/mortgage_2000-2001.tgzhttp://rapidsai-data.s3-website.us-east-2.amazonaws.com/notebook-mortgage-data/mortgage_2000-2001.tgz

docker run --runtime=nvidia --rm -it -v ~/data:/rapids/data -p 8888:8888 -p 8787:8787 -p 8786:8786 nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04

content of cell #4:
# to download data for this notebook, visit https://rapidsai.github.io/demos/datasets/mortgage-data and update the following paths accordingly
acq_data_path = "/rapids/data/mortgage/acq"
perf_data_path = "/rapids/data/mortgage/perf"
col_names_path = "/rapids/data/mortgage/names.csv"
start_year = 2000
end_year = 2001 # end_year is inclusive
part_count = 4 # the number of data files to train against

**Comment by dillon-cullinan** [comment]
If this is still an issue please create a new issue in the relevant repository, thank you!
