### ISSUE TITLE
Error using RAPIDS cuml KNN demo

### ISSUE THREAD

**Issue by drnemo22** [rapidsai/notebooks#106]
When trying to use KNN demo in RAPIDS using latest nvcr.io/nvidia/rapidsai/rapidsai:cuda9.2_ubuntu16.04 from December 6 2018 get following error:

code:
knn_cuml = cumlKNN(n_gpus=1)
knn_cuml.fit(X)
error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-ed085d756c19> in <module>
      1 get_ipython().run_line_magic('time', '')
      2 knn_cuml = cumlKNN(n_gpus=1)
----> 3 knn_cuml.fit(X)
      4 #D_cuml,I_cuml = knn_cuml.query(X,n_neighbors)

/conda/envs/rapids/lib/python3.5/site-packages/cuml-0+unknown-py3.5-linux-x86_64.egg/cuml.cpython-35m-x86_64-linux-gnu.so in cuml.KNN.fit()

AttributeError: module 'faiss' has no attribute 'StandardGpuResources'
----------
I have 2 GPU and when i modify code to specify 2 GPU i get this error:
code:
knn_cuml = cumlKNN(n_gpus=1)
knn_cuml.fit(X)
error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-25-c049da015ee5> in <module>
      1 get_ipython().run_line_magic('time', '')
      2 knn_cuml = cumlKNN(n_gpus=2)
----> 3 knn_cuml.fit(X)
      4 #D_cuml,I_cuml = knn_cuml.query(X,n_neighbors)

/conda/envs/rapids/lib/python3.5/site-packages/cuml-0+unknown-py3.5-linux-x86_64.egg/cuml.cpython-35m-x86_64-linux-gnu.so in cuml.KNN.fit()

/conda/envs/rapids/lib/python3.5/site-packages/faiss/__init__.py in index_cpu_to_all_gpus(index, co, ngpu)
    405     if ngpu == -1:
    406         ngpu = get_num_gpus()
--> 407     res = [StandardGpuResources() for i in range(ngpu)]
    408     index2 = index_cpu_to_gpu_multiple_py(res, index, co)
    409     return index2

/conda/envs/rapids/lib/python3.5/site-packages/faiss/__init__.py in <listcomp>(.0)
    405     if ngpu == -1:
    406         ngpu = get_num_gpus()
--> 407     res = [StandardGpuResources() for i in range(ngpu)]
    408     index2 = index_cpu_to_gpu_multiple_py(res, index, co)
    409     return index2

NameError: name 'StandardGpuResources' is not defined

when i let system use all GPUs and specify n_gpus=-1
code:
%time
knn_cuml = cumlKNN(n_gpus=-1)
knn_cuml.fit(X)
error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-af709e3a63c9> in <module>
      1 get_ipython().run_line_magic('time', '')
      2 knn_cuml = cumlKNN(n_gpus=-1)
----> 3 knn_cuml.fit(X)
      4 #D_cuml,I_cuml = knn_cuml.query(X,n_neighbors)

/conda/envs/rapids/lib/python3.5/site-packages/cuml-0+unknown-py3.5-linux-x86_64.egg/cuml.cpython-35m-x86_64-linux-gnu.so in cuml.KNN.fit()

/conda/envs/rapids/lib/python3.5/site-packages/faiss/__init__.py in index_cpu_to_all_gpus(index, co, ngpu)
    406         ngpu = get_num_gpus()
    407     res = [StandardGpuResources() for i in range(ngpu)]
--> 408     index2 = index_cpu_to_gpu_multiple_py(res, index, co)
    409     return index2
    410 

/conda/envs/rapids/lib/python3.5/site-packages/faiss/__init__.py in index_cpu_to_gpu_multiple_py(resources, index, co)
    393     resources. Handles the common case where the resources are assigned to
    394     the first len(resources) GPUs"""
--> 395     vres = GpuResourcesVector()
    396     vdev = IntVector()
    397     for i, res in enumerate(resources):

NameError: name 'GpuResourcesVector' is not defined

Thank you,
Andrew

**Comment by taureandyernv** [comment]
@drnemo22 can you please see if this issue is still existing and let us know?

**Comment by taureandyernv** [comment]
closing due to no response and I am having trouble reproducing the issue.  Also, @drnemo22  it seems that the FAISS module was being installed in Python 3.5, and RAPIDS requires 3.6 or 3.7.  Can you reopen if you still have trouble?  Thanks!
