### ISSUE TITLE
What is the difference between CUDA-X AI and RAPIDS?

### ISSUE THREAD

**Issue by vilmara** [rapidsai/notebooks#112]
**What is your question?**
Hi all, not sure if this is the right repository to ask this but couldn't find another one: What is the difference between CUDA-X AI and RAPIDS?, I see both are oriented to accelerate the complete end-to-end data science pipeline throw a collection of software libraries (most of them are common to both SDK such as cuDF, cuML, cuGRAPH, cuDNN).

RAPIDS suite is a data science ecosystem that can be used as a single unified tool via its containerized version https://ngc.nvidia.com/catalog/containers/nvidia:rapidsai:rapidsai. What about CUDA-X AI? 

I read that "CUDA-X AI is a collection of software-acceleration libraries built on top of CUDA. Its software-acceleration libraries are integrated into all deep learning frameworks, including TensorFlow, PyTorch, and MXNet, and popular data science software such as RAPIDS". Does it mean that RAPIDS is built on top of CUDA-X instead of the traditional version on CUDA?

**Comment by cjnolet** [comment]
Hi @vilmara, 

My short answer is that CUDA-X AI is a collection of software libraries for accelerating data science, which includes RAPIDS, but also deep learning libraries like cuDNN and TensorRT. RAPIDS Is a suite of tools for accelerating data science that includes specific tools for data wrangling, machine learning, and graph analytics. 

RAPIDS & the other CUDA-X AI libraries were all built using the same CUDA Runtime framework. 

These are great questions and I invite you to check out our Google Group and Slack channel, in hopes you might be able to get more detailed answers.

https://rapids.ai/community.html

**Comment by vilmara** [comment]
Hi @cjnolet, thanks for the reply!
