### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by StephenMSimpson** [rapidsai/notebooks#120]
## Report incorrect documentation

**Location of incorrect documentation**
The link to the mortgage dataset is incorrect - where should I be looking?
"Download the mortgage dataset for use with the notebook **here**" does not work.

<img width="1055" alt="Screenshot 2019-04-16 at 20 34 59" src="https://user-images.githubusercontent.com/37797638/56238880-761d6480-6087-11e9-87e2-5a50391392cb.png">

**Comment by taureandyernv** [comment]
Closing as we removed the mortgage notebook, it now lives in notebooks contrib, and we updated the docs there :).  Thanks @StephenMSimpson
