### ISSUE TITLE
Wrong file in notebooks/cuml/README.md

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#13]
Hi,

It seems that there is something incorrect in notebooks/cuml/README.md.

When it says:

* `dask-setup.sh`: notebook showcasing truncated singular value decomposition (tsvd) algorithm comparison between cuML and scikit-learn.

I think it should say:

* `tsvd_demo`: notebook showcasing truncated singular value decomposition (tsvd) algorithm comparison between cuML and scikit-learn.

Hope it helps!
Miguel

**Comment by mt-jones** [comment]
Resolved by PR https://github.com/rapidsai/notebooks/pull/15

**Comment by taureandyernv** [comment]
Closed as it is resolved by PR#15
