### ISSUE TITLE
No /rapids/data/mortgage/ directory on container  rapidsai:cuda9.2_ubuntu16.04

### ISSUE THREAD

**Issue by manuelreyesgomez** [rapidsai/notebooks#14]
The site detailing the data needed for the notebook:

https://rapidsai.github.io/demos/datasets/mortgage-data

And the notebook it self make references to the /rapids/data/mortgage/ directory, but it does not exist, and as the directory has to be created at a root level, one does not have permission to create it

So one needs to download the data somewhere else and change the paths on the notebook accordingly.

It would be easier for the user if there was a default /rapids/data/mortgage/ directory on the container and then instruct the users to unzip the data there. Then there is no need for changing paths on the notebooks

**Comment by taureandyernv** [comment]
fixed in notebooks extended.  Thanks @manuelreyesgomez !
