### ISSUE TITLE
"from cuml import Lasso" import error

### ISSUE THREAD

**Issue by jinli-ece-cs** [rapidsai/notebooks#149]
While running the first cell containing "from cuml import Lasso as cuLasso" in notebooks/cuml/coordinate_descent_demo.ipynb, encountered "ImportError: cannot import name 'Lasso'". Environment is from the image nvcr.io/nvidia/rapidsai/rapidsai:cuda9.2-runtime-ubuntu16.04.

**Comment by taureandyernv** [comment]
@jinli-ece-cs, is this the latest container with 0.7?

**Comment by taureandyernv** [comment]
@jinli-ece-cs i'm going to assume that this is no longer an issue, as we haven't heard from you and it has been working for us for the last 2 versions.  Please reopen if it still is a problem.  Thanks again!
