### ISSUE TITLE
[BUG] kNN notebooks typos

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#151]
**Describe the bug**
The first cell in the knn_demo.ipynb notebook says (relevant words in bold):

> ... 
> 2. should_downcast:bool (default = False). Currently only single precision is supported in the underlying undex. Setting this to true will allow **single-precision** input arrays to be automatically downcasted to **single precision**. Default = False.
> ...

I think it should be changed to (relevant words in bold):
> ... 
> 2. should_downcast:bool (default = False). Currently only single precision is supported in the underlying undex. Setting this to true will allow **double-precision** input arrays to be automatically downcasted to **single precision**. Default = False.
> ...

Hope it helps.

Regards,
Miguel

**Comment by miguelangel** [comment]
Also, cell #5 says:

> # the number of neighbors **whos** labels are to be checked

I think it should be said:

> # the number of neighbors **whose** labels are to be checked

Hope it helps.

**Comment by miguelangel** [comment]
One more thing, cell #6 says:

`knn_sk = skKNN(metric = 'sqeuclidean', )`

I would suggest changing it as follows:

`knn_sk = skKNN(metric = 'sqeuclidean')`

**Comment by miguelangel** [comment]
Hi @taureandyernv ,

Have you had the chance to review the comments above?

Thanks!

Miguel

**Comment by miguelangel** [comment]
Hi,

It looks this issue is still live in the latest version of the code:

https://github.com/rapidsai/notebooks-contrib/blob/branch-0.12/colab_notebooks/knn_demo_colab-0.8.ipynb

Please, assign it to me. I will submit a PR next week.

Regards,
Miguel

**Comment by taureandyernv** [comment]
Thanks Miguel!  Merged it.  I'm going to close the issue, but please reopen it as you see fit!
