### ISSUE TITLE
[BUG] Remove deprecated warning on sgd_demo.ipynb sample notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#153]
**Describe the bug**
In **sgd_demo.ipynb** notebook, cell #8 outputs a deprecated warning:

![image](https://user-images.githubusercontent.com/26169771/57815695-bea86a80-7778-11e9-80cb-f4dfffdcaa28.png)

It can be easily avoided by using **max_iter** instead of **n_iter**.

Hope it helps!
Miguel

**Comment by taureandyernv** [comment]
closed with https://github.com/rapidsai/notebooks/pull/157
