### ISSUE TITLE
[BUG] Remove un-needed import in sgd_demo.ipynb notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#155]
**Describe the bug**
Hi,

It looks like sgd_demo.ipnb notebook contains the following import, which is not used anymore:

> from sklearn.linear_model import SGDClassifier

**Steps/Code to reproduce bug**
Open notebook at https://github.com/rapidsai/notebooks/blob/branch-0.7/cuml/sgd_demo.ipynb

**Expected behavior**
Un-needed import to be removed.

**Comment by taureandyernv** [comment]
Thanks @miguelangel.  Fixed with https://github.com/rapidsai/notebooks/pull/159
