### ISSUE TITLE
[BUG] SVD algorithm in linear regression notebook produce larger error than EIG

### ISSUE THREAD

**Issue by alawami** [rapidsai/notebooks#161]
**Describe the bug**

SVD algorithm in linear regression notebook produce larger error than EIG on Rapids 0.6

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

Run the notebook:

https://github.com/rapidsai/notebooks/blob/branch-0.7/cuml/linear_regression_demo.ipynb

On NGC container:

0.7-cuda10.0-devel-ubuntu18.04-gcc7-py3.6

**Expected behavior**

SVD is expected to produce smaller error than EIG.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of RAPIDS libraries install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - If other methods, provide the commands used

On NGC container:

0.7-cuda10.0-devel-ubuntu18.04-gcc7-py3.6
 

**Additional context**

**Comment by taureandyernv** [comment]
Hey @alawami, its awesome that you saw this, and made an issue about it.  However, this issue should be posted in the cuml repo.  Can you repost it there while i get the right RAPIDS team members on it?

@JohnZed, can you check this out with your team?  Thanks!
