### ISSUE TITLE
[QST] Connecting to the Scheduler and the Dashboard

### ISSUE THREAD

**Issue by khcs** [rapidsai/notebooks#164]
**What is your question?**

Setup Dask
If I'm running the notebook inside a containder on a remote server, how do I connect to the Scheduler and the Dashboard? 127.0.0.1:35351 or 127.0.0.1:8787 does not work.

**Comment by taureandyernv** [comment]
127.0.0.1 is localhost for whatever that remote sever or host machine that container is on.  You may need to use ```<remote_ip_address>:35351``` or ```<remote_ip_address>:8787 to connect from your local machine.  If it is AWS, and you didn't enable the firewall to allow connections from everywhere, there are directions for port forwarding so that will let you connect through your SSH tunnel (which then you'd use 127.0.0.1:<port>)

Please let me know if you need any further help on our Slack channel rapids-goai.slack.com

**Comment by dillon-cullinan** [comment]
Please open a new issue if your issue persists in the relevant repository. Thanks!
