### ISSUE TITLE
[BUG] NVRTC error for DBSCAN Demo

### ISSUE THREAD

**Issue by punnu35** [rapidsai/notebooks#166]
I started a docker session with the rapids:latest image on nvidia compute lab. Ran through the DBSCAN notebook in the tutorial and got this error which converting pandas DF to CuDF. pandas DF look right on inspection.

---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
cudf/bindings/binops.pyx in cudf.bindings.binops.apply_op()

cudf/bindings/binops.pyx in cudf.bindings.binops.apply_compiled_op()

cudf/bindings/cudf_cpp.pyx in cudf.bindings.cudf_cpp.check_gdf_error()

GDFError: b'GDF_UNSUPPORTED_DTYPE'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-77340dd495d0> in <module>
      3 
      4 X_df = pd.DataFrame({'fea%d'%i: X[:, i] for i in range(X.shape[1])})
----> 5 X_gpu = cudf.DataFrame.from_pandas(X_df)

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in from_pandas(cls, dataframe, nan_as_null)
   2336         else:
   2337             index = dataframe.index
-> 2338         return df.set_index(index)
   2339 
   2340     def to_arrow(self, preserve_index=True):

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in set_index(self, index)
    771             df._index = index
    772             for k in self.columns:
--> 773                 df[k] = self[k].set_index(index)
    774             return df
    775 

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in __setitem__(self, name, col)
    277             self._cols[name] = self._prepare_series_for_add(col)
    278         else:
--> 279             self.add_column(name, col)
    280 
    281     def __delitem__(self, name):

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in add_column(self, name, data, forceindex)
    914         if isinstance(data, GeneratorType):
    915             data = Series(data)
--> 916         series = self._prepare_series_for_add(data, forceindex=forceindex)
    917         series.name = name
    918         self._cols[name] = series

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py in _prepare_series_for_add(self, col, forceindex)
    890 
    891         empty_index = len(self._index) == 0
--> 892         if forceindex or empty_index or self._index.equals(series.index):
    893             if empty_index:
    894                 self._index = series.index

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py in equals(self, other)
    215             return bool(val)
    216         else:
--> 217             result = (self == other)
    218             if isinstance(result, bool):
    219                 return result

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py in __eq__(self, other)
    188 
    189     def __eq__(self, other):
--> 190         return self._apply_op('__eq__', other)
    191 
    192     def __ne__(self, other):

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py in _apply_op(self, fn, other)
    133         op = getattr(idx_series, fn)
    134         if other is not None:
--> 135             return as_index(op(other))
    136         else:
    137             return as_index(op())

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/series.py in __eq__(self, other)
    556 
    557     def __eq__(self, other):
--> 558         return self._unordered_compare(other, 'eq')
    559 
    560     def equals(self, other):

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/series.py in _unordered_compare(self, other, cmpops)
    540         nvtx_range_push("CUDF_UNORDERED_COMP", "orange")
    541         other = self._normalize_binop_value(other)
--> 542         outcol = self._column.unordered_compare(cmpops, other._column)
    543         result = self._copy_construct(data=outcol)
    544         result.name = None

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/numerical.py in unordered_compare(self, cmpop, rhs)
     76 
     77     def unordered_compare(self, cmpop, rhs):
---> 78         return numeric_column_compare(self, rhs, op=cmpop)
     79 
     80     def ordered_compare(self, cmpop, rhs):

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/numerical.py in numeric_column_compare(lhs, rhs, op)
    353 
    354 def numeric_column_compare(lhs, rhs, op):
--> 355     return numeric_column_binop(lhs, rhs, op, out_dtype=np.bool_)
    356 
    357 

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/numerical.py in numeric_column_binop(lhs, rhs, op, out_dtype)
    338     out = columnops.column_empty_like(lhs, dtype=out_dtype, masked=masked)
    339     # Call and fix null_count
--> 340     null_count = cpp_binops.apply_op(lhs, rhs, out, op)
    341 
    342     out = out.replace(null_count=null_count)

cudf/bindings/binops.pyx in cudf.bindings.binops.apply_op()

cudf/bindings/binops.pyx in cudf.bindings.binops.apply_jit_op()

RuntimeError: NVRTC error: NVRTC_ERROR_INVALID_OPTION

**Comment by cjnolet** [comment]
@punnu35, the DBSCAN notebook has gotten a few updates since this issue was opened. Can you verify if this issue still persists?
