### ISSUE TITLE
[QST] TimeoutError: Worker failed to start

### ISSUE THREAD

**Issue by PadmarajBhat** [rapidsai/notebooks#185]
**What is your question?**

Installed latest dask on colab using  ```pip install dask_cuda```

Below is the stacktrace:

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-15-d68facff4369> in <module>()
      1 from dask_cuda import LocalCUDACluster
      2 
----> 3 cluster = LocalCUDACluster(scheduler_port=0, n_workers=1)
      4 client = Client(cluster)

19 frames
/usr/local/lib/python3.6/dist-packages/distributed/deploy/local.py in _start_worker(self, death_timeout, **kwargs)
    227         if w.status == 'closed' and self.scheduler.status == 'running':
    228             self.workers.remove(w)
--> 229             raise gen.TimeoutError("Worker failed to start")
    230 
    231         raise gen.Return(w)

TimeoutError: Worker failed to start

**Comment by taureandyernv** [comment]
@PadmarajBhat [We no longer support pip.](https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472)  Can you try conda install as per the [getting started page](https://rapids.ai/start.html) and report back if that solves your issue?  Thanks!

**Comment by PadmarajBhat** [comment]
I did go through the getting started page. Surprisingly, now even cudf also does not work.

I tried steps in https://github.com/rapidsai/notebooks-extended/blob/master/utils/rapids-colab.sh to install but still it says 


```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-b47e67134475> in <module>()
----> 1 import cudf
      2 df = dask-cudf.DataFrame()
      3 df['key'] = [0, 1, 2, 3, 4]
      4 df['val'] = [float(i + 10) for i in range(5)]  # insert column
      5 print(df)

ModuleNotFoundError: No module named 'cudf'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by PadmarajBhat** [comment]
This worked for me:

As indicated in the BlazingSQL startup guide following steps in Colab worked:
1. Confirm that T4 Tesla GPU is availed in colab.
2. Issue the command 
    ```
    !bash -c "$(wget -q https://s3.amazonaws.com/blazingsql-colab/install.sh -O -)"
    ```
3. In colab, Runtime -> Restart Runtime (or Ctrl +M)
4. Import cudf

Note that this is not a solution for dask_cudf issue mentioned in the initial problem but as indicated in dask_cudf, soon or later cudf would have dask_cudf functionality and we would have have to go only with cudf. In the current scenario,  the colab notebook does not successfully completes cudf import statement and hence I believe, the above solution is appropriate for the issue.

And for the distributed concern, it is rather better to go with https://dbdb.io/db/blazingsql instead to dask. Blazingsql might use dask at backend but it is transparent to developer.
