### ISSUE TITLE
[BUG] INtro notebook don't work at cuDF

### ISSUE THREAD

**Issue by xiaodaigh** [rapidsai/notebooks#219]
https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#forceEdit=true&offline=true&sandboxMode=true&scrollTo=EwaJSKuswsNi

The above is the link to your colab notebook. When i get to the cuDF section it says. It's easy to replicate just run step 1 - 3 then step 4 fails.

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-77b6558ae5dc> in <module>()
----> 1 import nvstrings, nvcategory, cudf
      2 import io, requests
      3 
      4 # download CSV file from GitHub
      5 url="https://github.com/plotly/datasets/raw/master/tips.csv"

ModuleNotFoundError: No module named 'nvstrings'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by taureandyernv** [comment]
@xiaodaigh great catch!  I actually PRed a fixed colab and link last week, and we're moving through QA right now, however it is in a private repo.  It should be available in the next couple days.

**Comment by xiaodaigh** [comment]
Wouldn't say it's a great catch. It was just there and I wanted to try out the notebook the first thing it does is fail! Not a great user-experience

**Comment by taureandyernv** [comment]
@xiaodaigh you're absolutely right about the first time user experience and we're constantly trying to improve it.  This Colab was one of our first, and sadly got left behind in the updates, and when it got updated, required a brand new link.  The good news is, in the back end, it will be much easier to keep this new link updated.  

The new link was just merged into the rapids.ai site staging.  Here's the new link if you'd like to try it out.  https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0#forceEdit=true&offline=true&sandboxMode=true

**Comment by taureandyernv** [comment]
Validated it all works using the new P100s from Colab.  Closing the issue as it has been resolved!  Thanks @xiaodaigh
