### ISSUE TITLE
[BUG] cuML notebooks need to be updated for new numpy API

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/notebooks#250]
**Describe the bug**
`PCA_demo`, `TSVD_demo`, and `holtwinters_demo_full` all should be updated to work with numpy 1.17, or numpy 1.16 with `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1`

(all cudf Series used in these NBs should be converted using something like `cudf.series.to_gpu_array()` )

**Steps/Code to reproduce bug**
Run the above notebooks in an environment with numpy 1.17 installed, or numpy 1.16 with `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1` and observe errors such as:
```
no implementation found for 'numpy.allclose' on types that implement __array_function__: [<class 'numpy.ndarray'>, <class 'cudf.core.series.Series'>]
```

**Expected behavior**
In the same environment, the above error should not be present.

cc @dantegd @cjnolet

**Comment by Salonijain27** [comment]
I believe this PR should solve these issues #255

**Comment by taureandyernv** [comment]
@rlratzel ,  can you confirm that PR #255  closes this issue? @Salonijain27

**Comment by taureandyernv** [comment]
Closing as it seems to have solved it.  Please reopen if anything new crops up!
