### ISSUE TITLE
[FEA] Update notebooks to make use of cuml train_test_split method

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#253]
**Is your feature request related to a problem? Please describe.**
Hi,

I have noticed that some notebooks still make use of sklearn `train_test_split `method.

I would suggest to showcase cuml's `train_test_split_method`, and run the `.to_pandas()` method if in any notebook it is needed to have the dataframe in host memory to run sklearn on it.

One example of notebook that might be updated is the following:

https://github.com/rapidsai/notebooks/blob/branch-0.11/cuml/random_forest_mnmg_demo.ipynb

Other notebooks that might need to be updated can be found by running the following query:

https://github.com/rapidsai/notebooks/search?q=train_test_split&unscoped_q=train_test_split

Hope it helps!

Regards,
Miguel

**Describe the solution you'd like**
To do not use sklearn train_test_split method, but cuml's version.

**Additional context**
@taureandyernv , I could submit a PR for this issue, if needed. If you are happy with that, just assign this issue to me.

**Comment by taureandyernv** [comment]
I'll take you up on your offer @miguelangel :)

**Comment by miguelangel** [comment]
Hi @taureandyernv ,

I have updated the `linear_regression_demo.ipynb` notebook.  Please, find attached the new version in PDF



I have performed the following changes:
- Move imports as close as possible to their usage
- Used cuml's version of `make_regression` and `train_test_split` methods.

Added cell #6 to copy data from GPU memory to host memory, to be able to compare CPUs and GPUs version of the algorithm.

If you are happy with these changes/approach, I will update the following notebooks accordingly, and submit a PR for review.

In the meanwhile, have an awesome weekend!

Regards,
Miguel

[linear_regression_demo.pdf](https://github.com/rapidsai/notebooks/files/3882587/linear_regression_demo.pdf)
 format.

**Comment by miguelangel** [comment]
Covered in #270 .
