### ISSUE TITLE
E2E failed at the stage of ETL: notebooks/mortgage/E2E.ipynb

### ISSUE THREAD

**Issue by huangsongjue** [rapidsai/notebooks#26]
### system info:
CPU: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz * 2
Memory: 128GB
GPU: NVIDIA V100 (16GB) x 1
OS: CenOS 7.5
CUDA: 9.2
CuDNN: 7.3
Tensorflow: 1.12

when I try to run notebooks/mortgage/E2E.ipyn,  everything seems fine at the beginning, then when I run into the ETL section,  dask-worker goes down and only dask-scheduler left then the training task hangs at 
- wait(gpu_dfs).

**Comment by taureandyernv** [comment]
Thanks for your bug finding, @huangsongjue , but i am closing this issue as this notebook has been updated quite a few times since you've filed this.  If you still have a problem, please reopen this issue with an update.  Thanks!
