### ISSUE TITLE
add teardown process for dask cluster [FEA]

### ISSUE THREAD

**Issue by em-watkins** [rapidsai/notebooks#27]
Currently, it seems that the dask cluster can be shut down by exiting the entire rapids container or by starting a new cluster via dask-setup.sh. 
Since cluster teardown is not triggered at shutdown of jupyter kernel or jupyter notebook server, perhaps the shutdown flow in dask-setup.sh can be split into a separate util so one can continue other rapids work inside the container.

**Comment by datametrician** [comment]
+@mrocklin 
Maybe this should be in dask-cuDF?

**Comment by mrocklin** [comment]
I'm inclined to remove the use of the dask-setup script entirely.

I've been using https://github.com/mrocklin/dask-cuda recently and have been happy with it.  I encourage others to try it out and provide feedback.  Hopefully that can improve the situation generally.

The `LocalCUDACluster` class there inherits from Dask's normal `LocalCluster`, which handles cleanup decently well.

**Comment by datametrician** [comment]
Let's get dask-cuda in the 0.5 release then

**Comment by em-watkins** [comment]
@mrocklin thanks for integrating dask-cuda. 
Should we expect `client.close()` to work on a client started with the LocalCUDACluster method? 

When I run that command, it doesn't seem to have any affect on the client. I still see all the workers in the DASK UI, & all its python processes are still active. 

repro: start cluster like in E2E mortgage notebook: 
https://github.com/rapidsai/notebooks/blob/9c5af2fba17671bf1aa811652094f317702f11aa/mortgage/E2E.ipynb
```
cmd = "hostname --all-ip-addresses"
process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
IPADDR = str(output.decode()).split()[0]

cluster = LocalCUDACluster(ip=IPADDR)
client = Client(cluster)
client
```
`client.close()` doesn't shut down the client. 


I'm using a prebuilt rapidsai image: 
`https://github.com/rapidsai/dask-cuda.git`
`e40519462aaeb3aeca87d3bffe3c76a88e3952f0`

**Comment by mrocklin** [comment]
I suspect that it is closing down the client (The thing from which you
submit tasks to the cluster) but it doesn't close down the *cluster* which
is what you really want to do.  My guess is that you're looking for
cluster.close()

**Comment by em-watkins** [comment]
Interesting, thanks. `cluster.close()` does shut down the workers and not the client. 
When I was working with dask directly, `client.close()` appeared to be shutting down both the client and the cluster. 
(Client was started via `client = Client(threads_per_worker=1, n_workers=2`.)

**Comment by mrocklin** [comment]
See http://docs.dask.org/en/latest/futures.html#distributed.Client.close

**Comment by em-watkins** [comment]
Great, thanks! 

btw, not sure why that page has more detailed info than its sister page: http://docs.dask.org/en/latest/setup/single-distributed.html

**Comment by randerzander** [comment]
@em-watkins is this ok to close?

**Comment by em-watkins** [comment]
Yes. Thanks very much!
