### ISSUE TITLE
[BUG] SSSP notebook is corrupted

### ISSUE THREAD

**Issue by afender** [rapidsai/notebooks#285]
**Describe the bug**
cugraph/traversal/SSSP.ipynb renders properly on GitHub but looks corrupted when opened with Jupyter

**Steps/Code to reproduce bug**
Open the notebook

**Additional context**
![Screenshot from 2019-12-20 13-50-32](https://user-images.githubusercontent.com/45606510/71288123-d9a31480-232f-11ea-98f0-dc05425743e0.png)

**Comment by taureandyernv** [comment]
Solved in #284.  awaiting approvals to merge
