### ISSUE TITLE
[CUML] Benchmarking notebook

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/notebooks#31]
I have created a reusable benchmark notebook for the cuML algorithms. It outputs an image of chart to demonstrate the speedup (or slowdown) from the corresponding algorithms in sklearn. I will submit a PR for this.

**Comment by taureandyernv** [comment]
Hey cjnolet, can you link to the PR that has these benchmarking notebooks when you do them?

**Comment by taureandyernv** [comment]
PR submitted, and merged into Notebooks extended.
