### ISSUE TITLE
NGC Rapids usage instructions outdated

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#53]
Hi,

At https://ngc.nvidia.com/catalog/containers/nvidia:rapidsai:rapidsai, the instructions under 

_Start Container and Notebook Server_

refer to an old version of the RAPIDS container, which might point users to start working with an older version of RAPIDS.

Hope it helps.

Regards,

Miguel

**Comment by mike-wendt** [comment]
These instructions are the latest. `cuda9.2-runtime-ubuntu16.04` as used in the example is a new container image that was deployed on 1/31 with v0.5.

I believe we can close this, please confirm.

**Comment by miguelangel** [comment]
You are right @mike-wendt. Somehow, I mixed the tags.

Closing now...
