### ISSUE TITLE
[Documentation Error]: incorrect name of script to invoke jupyter-lab

### ISSUE THREAD

**Issue by tym1062** [rapidsai/notebooks#54]
Typo on this web-page: https://rapids.ai/documentation.html.  Need to change name of script, replace underscore ("_") to hyphen ("-") for script to start jupyter lab within the container images.

Change: bash utils/start_jupyter.sh

To: bash utils/start-jupyter.sh

**Comment by mike-wendt** [comment]
Updated on NGC and DH as well as the web site...

The site has been updated so the new page is at this link https://rapids.ai/start.html
