### ISSUE TITLE
[BUG] matplotlib library not found

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#59]
**Describe the bug**
When running _linear_regression_demo.ipynb_ or _ridge.ipynb_, the following error is displayed because matplotlib library is not in the container:

> ModuleNotFoundErrorTraceback (most recent call last)
> <ipython-input-1-7278fb7c3aa4> in <module>
>       6 import cudf
>       7 import os
> ----> 8 from matplotlib import pyplot as plt
> 
> ModuleNotFoundError: No module named 'matplotlib'

**Steps/Code to reproduce bug**
docker pull nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04

bash utils/start-jupyter.sh

localhost:8888

run _linear_regression_demo.ipynb_ or _ridge.ipynb_

**Expected behavior**
No error found.

**Environment details (please complete the following information):**
DGX-1 

**Additional context**

**Comment by mike-wendt** [comment]
@miguelangel there is a work around by from @randerzander executing this in a cell within the notebook:

```
!conda install -y matplotlib scikit-learn
```

@randerzander @taureandyernv how should we solve this? by placing it in the notebook? I think it makes it easier to manage dependencies that way instead of trying to make sure a container has all dependencies

**Comment by miguelangel** [comment]
Hi @mike-wendt,

I am not 100% sure the work around is the best solution for many enterprise users. Many of them have limited or none access to internet. 

Regards,
Miguel

**Comment by taureandyernv** [comment]
Removed dependency on matplotlib from notebooks in question with PR #67
