### ISSUE TITLE
[DOC] rename _ridge.ipynb_ to _ridge_demo.ipynb_ in order to be consistent with the other notebooks names

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#60]
## Report incorrect documentation
_ridge.ipynb_ notebooks does not follow the name convention of the other notebooks in the _cuml_ folder (they all finish with the suffix _\_demo_.

**Location of incorrect documentation**
https://github.com/rapidsai/notebooks/tree/master/cuml

**Describe the problems or issues found in the documentation**
Not all the notebooks follow the same name convention (_ridge.ipynb_ should be _ridge_demo.ipynb_).

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**
Rename the notebook
---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by taureandyernv** [comment]
Resolving in PR https://github.com/rapidsai/notebooks/pull/67

**Comment by taureandyernv** [comment]
Integrated.  Thanks @miguelangel !
