### ISSUE TITLE
[DOC] cuml/README.md does not cover all the notebooks

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#61]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/notebooks/blob/master/cuml/README.md

**Describe the problems or issues found in the documentation**
It does not mention other algorithm sample notebooks, such as pca, ridge, linear regression...

**Steps taken to verify documentation is incorrect**
I have read the README.md, and compare its content to the cuml content.

**Suggested fix for documentation**
Add documentation for the new notebooks.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by taureandyernv** [comment]
fixed! thanks @miguelangel
