### ISSUE TITLE
[BUG] linear_regression.ipynb and ridge.ipynb future warning 

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/notebooks#62]
**Describe the bug**
When running _cuml/linear_regression.ipynb_ or _cuml/ridge.ipynb_ notebooks, the following warning is displayed in cell #9.

> /conda/envs/rapids/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

**Steps/Code to reproduce bug**
ocker pull nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04

bash utils/start-jupyter.sh

localhost:8888

run _linear_regression_demo.ipynb_ or _ridge.ipynb_

**Expected behavior**
No warning displayed.

**Environment details (please complete the following information):**
DGX-1 

**Additional context**

**Comment by taureandyernv** [comment]
resolving in https://github.com/rapidsai/notebooks/pull/67

**Comment by taureandyernv** [comment]
Integreated.   Thanks @miguelangel !
