### ISSUE TITLE
[BUG] Additional Dependencies Required on Container: seaborn and termcolor

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/notebooks#66]
The notebook rapids_lsst_gpu_only_demo.ipynb will not run without pip installations of seaborn and termcolor. Those two libraries should ideally be added to the container spec.
Not sure where the Dockerfile for rapidsai/rapidsai is, but I'm happy to put in a PR.

**Comment by taureandyernv** [comment]
Hey @saifrahmed , we had a long internal discussion in response to your bug.  We have separated our core notebooks from those that require additional dependencies.  I also will have a PR where we do "try/except" and import the dependencies for you.  Thanks for your input and making RAPIDS a better project!
