### ISSUE TITLE
Add NYC Taxi notebook from cloud storage data

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/notebooks#71]
This is the go-to demo for dask dataframe (with Pandas)

https://github.com/dask/dask-docker/blob/master/notebook/examples/05-nyc-taxi.ipynb

*Hypothetically* we should be able to replace the `dd.read_csv` call with `dask_cudf.read_csv` and everything should just work.  That's almost certainly not true (something will break) but it would be good to start pushing on this and find out what.

cc @beberg (also, can you cc Ty or anyone you think might be good at doing benchmarks)

**Comment by mrocklin** [comment]
We'll probably need to remove the `parse_dates=` keyword from read_csv

**Comment by mrocklin** [comment]
I run into issues with 

```python
df.groupby(df.passenger_count).trip_distance.mean().compute()
```

where the following works

```python
df.groupby('passenger_count').trip_distance.mean().compute()
```

I'll try to boil this down to a minimal failing example and report upstream

**Comment by mrocklin** [comment]
Boiled down and reported here:

-  https://github.com/rapidsai/dask-cudf/pull/132
-  https://github.com/rapidsai/cudf/issues/1096

**Comment by mrocklin** [comment]
I also needed https://github.com/rapidsai/cudf/issues/49

**Comment by mrocklin** [comment]
I can hack around these problems to get the following workflow (only reading a small amount of data because I'm on a local machine, rather than GCP)

```python
import dask_cudf
df = dask_cudf.read_csv('gcs://anaconda-public-data/nyc-taxi/csv/2015/yellow_*.csv').partitions[:2].persist()
df.groupby('passenger_count').trip_distance.mean().compute().to_pandas()
```

```
0     2.109440
1    12.402242
2     2.950518
3     2.839572
4     2.867007
5     2.853978
6     2.766583
7     2.450000
8     4.118000
9     3.200000
dtype: float64
```

```python
df = df[df.tip_amount > 0]
df = df[df.fare_amount > 0]
df['hour'] = df.tpep_pickup_datetime.dt.hour
df.groupby('hour').trip_distance.mean().compute().to_pandas()
```

```
0      3.367328
1      3.722813
2      3.240690
3      3.410732
4      4.348283
5      5.229275
6      3.884735
7      3.024474
8      2.567245
9      2.534210
10     2.623676
11     2.607683
12     2.620929
13     2.731340
14     2.867120
15     2.978550
16     3.005126
17     2.770879
18     2.616566
19    26.937507
20     5.210856
21     3.108731
22     3.231892
23     3.351040
dtype: float64
```

I also got some nasty warnings when reading from GCS, I'm hoping that these have more to do with my local network settings though

```
Traceback (most recent call last):
  File "/home/nfs/mrocklin/miniconda/envs/cudf/lib/python3.7/site-packages/google/auth/transport/requests.py", line 120, in __call__
    **kwargs)
  File "/home/nfs/mrocklin/miniconda/envs/cudf/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nfs/mrocklin/miniconda/envs/cudf/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nfs/mrocklin/miniconda/envs/cudf/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf362b2128>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by vilmara** [comment]
hi @mrocklin, is there a sample that shows how to setup and read the data from NFS instead?

**Comment by mrocklin** [comment]
You seem to be working from an example that is very old.  We haven't used `Executor` for years now.  You might want to start at the docs or the examples.   https://docs.dask.org https://examples.dask.org

For the warnings I'm hoping that they're self explanatory regarding Executor/Client. 

For NFS, just use the path.

**Comment by vilmara** [comment]
hi @mrocklin, what prepend prefixe (like hdfs, s3, gcs) should use before the path to indicate the NFS location (it is connected over Infiniband)?

**Comment by mrocklin** [comment]
Nothing, just a normal file location like "/path/to/file.csv" or
"file.csv".  If you really want to be explicit you can use file://, but
this is unnecessary.

If a function like pandas.read_csv or cudf.read_csv can be passed the
filename you provide then that's all that matters.

**Comment by vilmara** [comment]
Thanks @mrocklin, it is working!
