### ISSUE TITLE
[BUG] cuML/KNN ImportError

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/notebooks#79]
**Describe the bug**
Did nbconvert and ran the resulting script. Got the TB below.  Not sure if it's related to the other KNN issue #68 on API changes (seems like it could be)
```
(rapids) root@803553dd81fd:/rapids/notebooks/cuml# python /tmp/knn_demo-test.py
Traceback (most recent call last):
  File "/tmp/knn_demo-test.py", line 10, in <module>
    from cuml import KNN as cumlKNN
ImportError: cannot import name 'KNN' from 'cuml' (/conda/envs/rapids/lib/python3.7/site-packages/cuml-0.5
.1+596.gb05d87e-py3.7-linux-x86_64.egg/cuml/__init__.py)  
```

**Steps/Code to reproduce bug**
`nbconvert` NB to get script, run script, see TB.

**Expected behavior**
no TB :)

**Environment details (please complete the following information):**
nightly container 

**Additional context**
n/a

**Comment by dantegd** [comment]
PR #72 should solve this

**Comment by randerzander** [comment]
closing now that #72 merged. Please re-open if still an issue

**Comment by Alluxia-F** [comment]
Trying to import cuml.neighbors but got the import error. 
Env.: Google colab.
import of cuml, and cudf are successful. 

https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0
