### ISSUE TITLE
[BUG] mortgage/E2E raises "NameError: name 'get_ipython' is not defined" on nightly container

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/notebooks#81]
**Describe the bug**
The nightly container testing for mortgage/E2E failed when the nbconvert'd script raised an exception:
```
  File "/tmp/E2E-test.py", line 38, in <module>
    get_ipython().run_line_magic('env', 'NCCL_P2P_DISABLE=1')
NameError: name 'get_ipython' is not defined
```

**Steps/Code to reproduce bug**
nbconvert the mortgage/E2E NB, run script using the (default) "rapids" conda env provided by the nightly container, observe traceback.

**Expected behavior**
No traceback :)

**Environment details (please complete the following information):**
Ubuntu (either version) nightly container
"rapids" conda environment 

**Additional context**
@randerzander mentioned that @mt-jones might have some info on this.

**Comment by taureandyernv** [comment]
bug fixed way back when....closing old issue
