### ISSUE TITLE
[BUG]branch-0.6-release: cuml/sgd_demo requires matplotlib

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/notebooks#87]
Hey @Salonijain27!

Just an important FYI: Notebooks in rapidsai/notebook should not have _any_ external dependencies to the docker container.

If `matplotlib` is truly required, please make a PR to the notebooks-extended repo and remove `sgd_demo`.  If it can be revised to not require it, please make the appropriate revisions and make a PR with the changes.

Thanks!

**Comment by rlratzel** [comment]
This is a duplicate of #80

**Comment by taureandyernv** [comment]
closed as this was fixed in 0.6
