### ISSUE TITLE
[BUG]TypeError: reraise() missing 2 required positional arguments: 'tp' and 'value'

### ISSUE THREAD

**Issue by StephenMSimpson** [rapidsai/notebooks#89]
**Describe the bug**
This is similar error message to bug report #65, however, I do have a Pascal GPU (admittedly only a P4).
I am clearly running out of memory (see trace at bottom). How do I know how much I need, and is there anything I can do to manage it (other than buying a DGX-n)? Where can I read more?

The trace is pasted at the bottom of this report.

**Steps/Code to reproduce bug**
I am running the standard mortgage demo (E2E.ipynb) provided with RAPIDS. The only modifications made to the notebook are to point to the Mortgage data files.

Training the gradient boosted decision tree fails
bst = dxgb_gpu.train(client, dxgb_gpu_params, gpu_dfs, labels, num_boost_round=dxgb_gpu_params['nround'])

**Expected behavior**
That training completes successfully.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of RAPIDS libraries install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
$ sudo docker pull rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04
$ sudo docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786     -v /home/RAPIDS_evaluation/data/2000-2016:/mortgage rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04

I have cuda 10.1 installed.

**Additional context**
I am getting an out of memory error on every mortgage file that gets loaded:
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x7ff392aba0d0>, <function run_gpu_workflow at 0x7ff36448e9d8>, [], (<class 'dict'>, [['quarter', 3], ['year', 2016], ['perf_file', '/mortgage/perf/Performance_2016Q3.txt']])))
kwargs:    {}
Exception: Exception('GDF_MEMORYMANAGER_ERROR',)

Stack trace listed below:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

/conda/envs/rapids/lib/python3.6/site-packages/dask_xgboost-0.1.5-py3.6.egg/dask_xgboost/core.py in train(client, params, data, labels, dmatrix_kwargs, **kwargs)
    229     """
    230     return client.sync(_train, client, params, data,
--> 231                        labels, dmatrix_kwargs, **kwargs)
    232 
    233 

/conda/envs/rapids/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    673             return future
    674         else:
--> 675             return sync(self.loop, func, *args, **kwargs)
    676 
    677     def __repr__(self):

/conda/envs/rapids/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

/conda/envs/rapids/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/conda/envs/rapids/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

/conda/envs/rapids/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/conda/envs/rapids/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

/conda/envs/rapids/lib/python3.6/site-packages/dask_xgboost-0.1.5-py3.6.egg/dask_xgboost/core.py in _train(client, params, data, labels, dmatrix_kwargs, **kwargs)
    163     for part in parts:
    164         if part.status == 'error':
--> 165             yield part  # trigger error locally
    166 
    167     # Because XGBoost-python doesn't yet allow iterative training, we need to

/conda/envs/rapids/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/conda/envs/rapids/lib/python3.6/asyncio/tasks.py in _wrap_awaitable(awaitable)
    535     that will later be wrapped in a Task by ensure_future().
    536     """
--> 537     return (yield from awaitable.__await__())
    538 
    539 

/conda/envs/rapids/lib/python3.6/site-packages/distributed/client.py in __await__(self)
    377 
    378     def __await__(self):
--> 379         return self.result().__await__()
    380 
    381 

/conda/envs/rapids/lib/python3.6/site-packages/distributed/client.py in result(self, timeout)
    193                                   raiseit=False)
    194         if self.status == 'error':
--> 195             six.reraise(*result)
    196         elif self.status == 'cancelled':
    197             raise result

TypeError: reraise() missing 2 required positional arguments: 'tp' and 'value'
[ ]:

**Comment by taureandyernv** [comment]
Hey, we're noticing this too.  It means ETL failed earlier on.  Did you get a bunch of nanny warnings, @StephenMSimpson ?

**Comment by StephenMSimpson** [comment]
Yes, I do get a few nanny warnings in the Notebook, and I can see the processes being restarted on the nvidia-smi display (I make sure I start with a GPU with no processes attached).

distributed.nanny - WARNING - Worker process 50 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process 69 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker

So, it looks as though I am simply blowing the GPU memory in the ETL phase (nvidia-smi shows that process name /conda/envs/rapids/bin/python has consumed 7595MiB, but I only have 7605/7611MiB).

Is there any way to throttle things, or is this just "how it is" (i.e. the architecture assumes a sufficient number of GPUs with sufficient collective memory to handle whatever is thrown at it)? Do we have the equivalent of virtual memory management, so we can page things out if memory allocation reaches its threshold? (I know that it defeats the object of the exercise; however, you also want things to run to be able to run to completion ;-) )
