### ISSUE TITLE
[FEA] update the E2E.ipnb so it can work with newer cudf versions(v0.6, v0.7)

### ISSUE THREAD

**Issue by huangsongjue** [rapidsai/notebooks#93]
**Is your feature request related to a problem? Please describe.**
the E2E notebook works well with cuDF v0.5, but error occured with cuDF v0.6 or v0.7:
> distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x7f023ff8ed90>, <function run_gpu_workflow at 0x7f02317486a8>, [], (<class 'dict'>, [['quarter', 1], ['year', 2001], ['perf_file', 'mortgage/perf_split/Performance_2001Q1.txt_0']])))
kwargs:    {}
Exception: KeyError('max_current_loan_delinquency_status') 

**Describe the solution you'd like**
update the notebook so cuDF v0.6/v0.7.

**Describe alternatives you've considered**

**Additional context**

**Comment by taureandyernv** [comment]
resolved and working with 0.6 and 0.7
