### ISSUE TITLE
[BUG] DeprecationWarning in sgd_demo notebook 

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/notebooks#94]
The SGDRegressor function of sklearn requires **n_iter** parameter to be passed to ensure that the algorithm runs for the specified number of epochs.  If the **max_iter** parameter is used then the algorithm does not run for the required number of epochs. 
Therefore, we get the following warning :
```
/conda/envs/rapids/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
```

**Comment by taureandyernv** [comment]
closed as this was fixed in 0.6
